### ISSUE TITLE
Keyring Auhtorization

### ISSUE THREAD

**Issue by websitesupport** [Automattic/eventbrite-api#23]
Hi,

I'm trying to authorize the keyring with eventbrite.
I'm 100% sure I have the correct API KEY and SECRET, but the moment I hit ALLOW, I keep getting these:

There was a problem authorizing with Eventbrite. Please try again in a moment.
Failed to load your request token while connecting to Eventbrite. Please try again in a moment.

Do you know where the problem could be?

**Comment by ads1018** [comment]
I'm still getting this error. Erasing the info on keyring and resaving doesn't do anything. What table is this data stored in? Perhaps I need to delete a table entry? ![image](https://user-images.githubusercontent.com/555740/30116551-d5e8aa7a-92eb-11e7-94b2-b57d1aeec029.png)

**Comment by ustarke13** [comment]
Make sure that when copying the codes you do not copy the space at the end!
