### ISSUE TITLE
no events found

### ISSUE THREAD

**Issue by mattvenn** [Automattic/eventbrite-api#27]
Hi there, I'm struggling to get this working on my website. Here's the page:
http://bristol.hackspace.org.uk/events/

I couldn't post on the wordpress issues page because I don't know my password and the password reset emails don't go through to my email.

Permalinks are simple. I also tried on twenty eleven theme with the same results.

Also, it seems a bit strange that you go to quite a lot of trouble to do good docs, but there isn't a single screenshot of it working or what to expect!

Thanks,
Matt

**Comment by kwight** [comment]
Hi Matt,

A few things to double-check:

* Is the Eventbrite Events template still set on that page? If you've been switching themes to test, it might not be.
* You have an active connection under Tools > Keyring. You can click the test link and get an A-OK.
* The account you're connected to has public events. By default, the plugin only works with public events, so if they're all marked private, you'll get no events back in WP.

Let me know if any of this helped.

**Comment by mattvenn** [comment]
yes, events template is still on it

the keyring works and when I press 'test' that shows ok too

I made the event non-public because it's a test event. But I only did that after half an hour of fiddling around. I've made it public again so you can check.

**Comment by kwight** [comment]
So now it might be the transient cache that's returning the empty results from before making the event public. The quickest way to delete the cache is to delete the Eventbrite connection in Keyring and connect again.

If that doesn't work, I'll need a look at your admin; you can make a temp admin account for me and email the creds to kwight@kwight.ca. Let me know, thanks.

**Comment by adamcoulombe** [comment]
Hey I had the same issue with the plugin not fetching newly added events.. I followed your instructions and it refreshed fine, so thank you!

I'm wondering though how I can use `Eventbrite_Query` in my page without having to worry about going in and refreshing my key each time a new event is added. 

I know 'eventbrite_get_events' has an option for this but I'm not sure how exactly this can be used in conjuction with the existing plugin set up

**Comment by kwight** [comment]
@adamcoulombe Yeah, it's a trade-off with caching: you want to use it as much as possible until something new gets added to Eventbrite, then you don't want it at all. I played with the idea of a cache-busting button, but that meant introducing UI just for that. The Keyring page can be modified, I think; I'll consider adding a button there.

**Comment by mattvenn** [comment]
thanks for the help on this. I still can't get it to work, and have given up now - using one of their embedded html widgets.

**Comment by adamcoulombe** [comment]
@kwight Can you do an automatic daily cache-bust? Or maybe make the interval an option. It doesnt make sense to rely on cache thats greater than a day old anyway IMO. Especially if you add new events regularly. I'd actually prefer no cache at all. I'd do the work myself and add a pull request but I'm not even really sure where the caching originates from within the plugin.

**Comment by kwight** [comment]
> I'd actually prefer no cache at all.

@adamcoulombe With API load times of a few seconds, believe me, you wouldn't :) That said, I'm thinking I agree one week was too conservative, and have changed it to one day. The value can also now be filtered.

**Comment by kwight** [comment]
@adamcoulombe Pushed v1.0.2 with this change to the .org plugin repo, should be live soon.

**Comment by adamcoulombe** [comment]
Cool thanks Kirk I'll take a look and grab the update! Appreciate the fix on this!

**Comment by kwight** [comment]
Cool, my pleasure. It's a good change!
