### ISSUE TITLE
eventbrite_event_time() should use settings from WordPress locale

### ISSUE THREAD

**Issue by Zodiac1978** [Automattic/eventbrite-api#30]
Of course I can overwrite this function, because eventbrite_event_time() is pluggable, but wouldn't it be smarter to have I18N on board in a PO/MO-file or using at least the locale settings from WordPress to configure the date/time output?

**Comment by Zodiac1978** [comment]
__(), _x(), etc. are used, but there is no load_plugin_textdomain call.

**Comment by kwight** [comment]
You're right, i18n can be better handled for sure. We tackle it when we can.

**Comment by kwight** [comment]
Event dates and times will respect admin settings now with 0443f86745a87cab2086cecf5bb76ffe9cb90384.
