### ISSUE TITLE
Authorisation problems maybe just a copy/paste problem

### ISSUE THREAD

**Issue by Zodiac1978** [Automattic/eventbrite-api#31]
I have lost two hours because of authorisation problems with Eventbrite API, but in the end it was just a simple copy/paste error. There was a space left at the end of the secret key and so it doesn't work all the time.

Maybe add a trim() to this field to avoid these simple problems for people like me ;)

**Comment by kwight** [comment]
That's a good suggestion; all authentication for the plugin is handled by Keyring, so you can post the suggestion here: https://wordpress.org/support/plugin/keyring
