### ISSUE TITLE
Wrong iFrame-ID is leading to "This event has not been published yet." error

### ISSUE THREAD

**Issue by Zodiac1978** [Automattic/eventbrite-api#32]
Correct link on eventbrite.com is:
http://www.eventbrite.com/tickets-external?eid=17063219549&ref=etckt

But iFrame tries to load:
//eventbrite.com/tickets-external?eid=2147483647&ref=etckt

Which is the wrong ID and so it displays just "This event has not been published yet.".

No idea what causes this. Any forum threads I found are not showing any solution because people went to other plugins, etc.

**Comment by kwight** [comment]
I've never been able to replicate this myself, and have a hard time troubleshooting others' installs without access to error logs and databases. It's been happening to a noticeable amount of users though, for sure.

One theory was that it was related to 32-bit operating systems (vs 64-bit OSs), but I believe at least one user said that wasn't the case for them.

**Comment by Zodiac1978** [comment]
Hosting server is 64 bit. And unfortunately I have no access to error logs or database on this shared hosting service. :(

**Comment by kwight** [comment]
Would you be willing to give me access to your eventbrite.com account, so I can set up some testing and maybe determine if it's account-related? If so, just email themes@wordpress.com, and I'll be happy to take a look. Without being able to ever replicate it, I can't think of much else to do.

**Comment by Zodiac1978** [comment]
Problem found: https://wordpress.org/support/topic/this-event-has-not-been-published-yet-again

32-bit mode PHP on 64 bit server. :/

**Comment by kwight** [comment]
Closing as `wontfix`; anyone wanting to keep using the plugin with a 32-bit install can follow these instructions here: http://wvega.com/850/getting-eventbrite-api-wordpress-plugin-to-work-on-systems-with-32-bit-builds-of-php/
