### ISSUE TITLE
Events pulled into a Custom Post Type

### ISSUE THREAD

**Issue by jeffcorey** [Automattic/eventbrite-api#43]
Nice plugin guys. We're looking to use on an upcoming project. Is it possible to pull the event directly into a custom post type instead of displaying them on pages? Any insight on this would be appreciated. Thanks

**Comment by kwight** [comment]
Hi jeffcorey,

Sure – you can use the helper functions or lower level utilities for the API calls, and then process them however you like. Take a look at `eventbrite_get_events()` and `eventbrite_search()` (in `inc/functions.php`), and to go deeper (bypassing validation, caching, etc to do yourself), just use the `Eventbrite_API` class.

**Comment by jeffcorey** [comment]
Thanks. I will look into this. Appreciate the quick response.

**Comment by kwight** [comment]
:+1: Let us know if you have any other questions.
