### ISSUE TITLE
Link to Github Page in Description

### ISSUE THREAD

**Issue by jamieisboss** [Automattic/eventbrite-api#46]
Dont know if it's a standard but it's starting to become a defcto one if it isnt, its useful and a lot of projects do it.

I'm thinking popping a link to http://automattic.github.io/eventbrite-api/ in the description; so it's at the top of the code page and, as they say in a dying matrix, ergo, easier to find/know exists, therefore would be a cool thing to do. 

(It's not like peer pressure, everyone's doing it)

**Comment by kwight** [comment]
Fixed in 7021a7f970543715a7133948912c7bd95c0ee64a
