### ISSUE TITLE
Not able to display correctly on knore theme with is by showthemes on wordpress

### ISSUE THREAD

**Issue by irelandherbal** [Automattic/eventbrite-api#47]
Hi there,
. I like the api key form evenbrite for wordpress because it looks that will resolve all the problems that I had in the past with eventbrite widget which is not responsive with iphone and a big mess.
Here I made a trial but a big mess. Because my theme which is khore from showthemes doesn't let me displayed this one well.

Have a look at here.

https://www.befitclub.ie/registration-test/

I believe it is something easier to resolve and someone will be able to help me here.

Thanks for taking the time to read this.

Thanks

**Comment by kwight** [comment]
Hi irelandherbal,

Yes, the output can be tailored to an individual theme – we can't do the work for you, but all the instructions are in this article (the Theme Support section) for any developer to follow. Good luck!
