### ISSUE TITLE
Address being output twice?

### ISSUE THREAD

**Issue by mark-making** [Automattic/eventbrite-api#52]
Using `eventbrite_event_venue()` with the `address` property seems to be outputting the address twice?

From what I can gather, it seems to pull in the event location, then the overall address of the event listing footer.

![example](https://cloud.githubusercontent.com/assets/22819787/19356296/44170656-9165-11e6-99d7-d9ec57ccfdc2.png)

📟  @kwight

**Comment by kwight** [comment]
The `eventbrite_event_venue()` function [returns](https://github.com/Automattic/eventbrite-api/blob/7021a7f970543715a7133948912c7bd95c0ee64a/inc/functions.php#L280) the full `venue` object from the API response, so to use the address, you'll need to reference and echo out the pieces you would like. The response is in this format:

![screen shot 2016-10-17 at 11 42 20 am](https://cloud.githubusercontent.com/assets/349751/19450629/127df72e-945f-11e6-819b-f95849f94bd0.png)

... so you'll need calls like `eventbrite_event_venue()->name` and `eventbrite_event_venue()->address->city` in your template to assemble the address you want to display, in whatever format you like.

**Comment by mark-making** [comment]
Thanks @kwight.
