### ISSUE TITLE
Why is there no Shortcode? 

### ISSUE THREAD

**Issue by le0nard0** [Automattic/eventbrite-api#57]
I have so many whys about this plugin. Likely I missed something so here is the question. 

Why is this a page template and not a shortcode?

This is virtually unusable with my theme. While asking the theme makers to make the theme Eventbrite optimized is a nice idea, it'll never happen before I need to go live. 

I'm going to end up manually linking to all of the events. What am I missing?

**Comment by karneaud** [comment]
+1

**Comment by kwight** [comment]
The intention of the plugin was to give theme developers a set of tools for easily integrating Eventbrite into their theme; by standardizing markup with the Underscores theme, it also allowed the plugin to often work out-of-the-box with many themes (or be [quickly adapted](https://themeshaper.com/2014/12/08/working-with-the-eventbrite-api-plugin/) for those needing further tweaking). Implementing this functionality through a shortcode _could_ be done, but I imagine it would be frustrating dealing with things like API call handling and pagination in a shortcode (and you would still have the same issues with mismatched markup or styling).

If all you want is a shortcode, then you're better to use [Eventbrite's own widgets](https://www.eventbrite.com/support/articles/en_US/How_To/how-to-sell-eventbrite-tickets-registrations-on-your-website-using-embeddable-widgets?lg=en_US). Again, you'll be stuck with their styling and branding, but they work well for non-customizable display of their content.
