### ISSUE TITLE
Event-index page fails on Windows servers

### ISSUE THREAD

**Issue by hardy613** [Automattic/eventbrite-api#58]
https://christattum.com/how-to-fix-a-blank-events-page-when-using-the-wordpress-eventbrite-api-plugin/

esc_url() works differently on Windows .... Now this is fine on Linux, since file paths begin with a ‘/’ and indeed the esc_url() function makes a special case for this and lets it through. But of course, on Windows, file paths begin with C:\ (drive letters), and esc_url() considers this invalid, so the path is discarded, and an empty string is returned. So we get an empty page!

**Comment by kwight** [comment]
Hm, that is definitely unfortunate. It would be an issue to [take up with core](https://core.trac.wordpress.org/) though – `esc_url()` is a very common function in all WordPress development (themes, plugins, and core itself), and not exclusive to this plugin.

**Comment by hardy613** [comment]
Thank you for following up. 

To those that find this, here is a possible solution:

```
// hack - add "C" as a protocol to allow local a windows style path through the esc_url() function
// Replace "C" as required for different drive letters.
function add_windows_drives_as_protocols( $protocols ) {

    $protocols[] = 'F';
    return $protocols;

}
add_filter ('kses_allowed_protocols', 'add_windows_drives_as_protocols' );
```

I should note though, this will only work if the project is at the drive root; otherwise the 
```
c:\folder1\folder2\wordpress
``` 
is returned as 
```
c:folder1folder2wordpress/wp-content/....
```

Which was my issue, this caused me to edit the plugin file:

```
inc/class-eventbrite-templates.php
```
to remove the esc_url(). This method is not recommended as we edit core plugin files. It would be great if a filter was added at this point so we can hook into it and control the path that is returned.

I do not believe this is an issue for core (nor should it be marked closed), I think this is for eventbrite to fix. One possible solution is recommended above.

Thank you for your time.

**Comment by PhilipRowe** [comment]
@kwight @hardy613 Why is `esc_url()` being used to escape a file path??? I'm fairly sure this is not what `esc_url()` was designed for and it's breaking eventbrite on my windows machine as well. Surely `sanitize_file_name()` would be more appropriate! ([function reference](https://codex.wordpress.org/Function_Reference/sanitize_file_name)) If `esc_url()` is used by other plugins/themes/core in this way then why do they work on my windows machine?

**Comment by kwight** [comment]
Note that you can also filter the results of `esc_url()` using the `clean_url` filter here: https://core.trac.wordpress.org/browser/trunk/src/wp-includes/formatting.php#L3858

We have no plans for better Windows interoperability, but with that filter, you'll be able to handle Windows file paths as you see fit.

**Comment by hardy613** [comment]
Great!

Thanks for all the help.
