### ISSUE TITLE
Issue with displaying recent events

### ISSUE THREAD

**Issue by mark-making** [Automattic/eventbrite-api#60]
Is there any control over how quickly the plugin will check for new updates from Eventbrite before they are displayed on your webpage? I seem to have to keep re-adding the connection in Keyring to 'kick' the website in displaying the most recent events.

**Comment by kwight** [comment]
You can install [this plugin](https://github.com/Automattic/eventbrite-api-cache-one-hour) (by ZIP) to shorten the default caching to one hour (or anything else you like [here](https://github.com/Automattic/eventbrite-api-cache-one-hour/blob/master/eventbrite-api-cache-one-hour.php#L16), or using that `eventbrite_cache_expiry` hook).

**Comment by mark-making** [comment]
Thanks @kwight, you are always here to help 💯
