### ISSUE TITLE
Event posted from Wordpress to Eventbrite won't stay Live

### ISSUE THREAD

**Issue by Roadsider** [Automattic/eventbrite-api#62]
Anyone know why we will post an event via our Wordpress site through The Events Calendar plugin, make it **Live** for Eventbrite and then come back later and find it as a **Draft**? 

For some reason, Live status isn't sticking. We've had this setup for well over a year, and only in the past month did this seem to break.

**Comment by kwight** [comment]
Hi Roadsider, that's a different plugn than this one. You can post to their forums here: https://wordpress.org/support/plugin/the-events-calendar

**Comment by Roadsider** [comment]
Sorry. I was thinking that this was related to the API, and not Events Calendar.
