### ISSUE TITLE
Trouble with API -- breaks sync after event edit

### ISSUE THREAD

**Issue by Roadsider** [Automattic/eventbrite-api#63]
When we make an edit to an established event in Wordpress already synced to Eventbrite, it breaks the connection to Eventbrite. I'm thinking this is an issue with the API. This problem only appeared recently after about a year of solid performance. 

Anyone suggest a fix?

**Comment by kwight** [comment]
Hi Roadsider, this plugin has nothing to do with the Events Calendar plugin, which uses its own methods to connect to the Eventbrite API; the two are not aware of each other at all (this plugin creates fake posts from the Eventbrite API results, and never adds posts to the WordPress site).
