### ISSUE TITLE
Eventbrite-api error calling custom templates - wordpress running on windows 2012r2 server 

### ISSUE THREAD

**Issue by smcascaid** [Automattic/eventbrite-api#64]
Hello,

I've got wordpress server running on windows 2012r2 server,  It appears that the Eventbrite Plugin is not fully compatible with Windows servers (specifically when calling custom templates).

I’ve managed to install and link the plugin with WordPress and Eventbrite following these steps: http://automattic.github.io/eventbrite-api/users.html

But when it comes to assigning the Page Attributes to an Eventbrite Event it doesn’t show on the dropdown like it says it should. I’ve looked at the FAQ’s and forums but still not sure why it’s not showing up.  It's seems to be an Eventbrite-api error calling custom templates when running wordpress on windows.

We have had no issues running other wordpress plugins in the windows environment in the past.

Please can you help?

Thanks Muna

**Comment by kwight** [comment]
I'm afraid we have no plans to improve Windows Server support beyond what there is already.

One workaround would be to assign the page template to your desired page right in the database. In the `xx_postmeta` table, add a `meta_key` of `_wp_page_template` with a `meta_value` of `eventbrite-index.php` to the `post_id` of the page you want to display your events.
