### ISSUE TITLE
Eventbrite an PHP 7 on wordpress

### ISSUE THREAD

**Issue by ledob44** [Automattic/eventbrite-api#66]
Hello everyone, I have your plugin on a wordpress and everything's working fine on PHP 5.6.30 but I put it on an PHP 7 server and all my events are empty, do you know this issue and what's the solution ?
Thanks to all

**Comment by kwight** [comment]
Hm, not sure; we have it working on PHP 7 across WordPress.com. Are you sure you still have active, upcoming events? If in doubt, disconnecting and reconnecting to Eventbrite in Keyring will force a call to the API if you think it might be cache related.

Do you get the events you expect when you check the API directly?

`https://www.eventbriteapi.com/v3/events/search/?user.id=XXXXX&token=XXXXX`

Your user ID is at Tools > Keyring > External ID in your WordPress admin, and the token can be found under Account Settings > App Management > Show Client Secret and OAuth Token > Your personal OAuth token in your eventbrite.com account.

Their <a href="https://www.eventbrite.com/developer/v3/quickstart/">Quick Start guide</a> also gives some handy tips in working directly with their API.

**Comment by ledob44** [comment]
Thanks for your answer, we finally downgraded the server to PHP  5.6.30 but we still had the issue on loops but not on the single event.
Finally it came from $this->post_api_filters(); in get_posts() function in class-eventbrite-query.php that emptied events array on Nginx server. I removed it and everything is now working fine.
