### ISSUE TITLE
Add Support For Eventbrite Widgets

### ISSUE THREAD

**Issue by harishankerr** [Automattic/eventbrite-api#69]
### The Issue

While the plugin provides a wonderful way to integrated Eventbrite events to a WordPress website, it does not create a widget (that lists upcoming events) - [similar to the functionality in WordPress.com](https://harishankerblog.wordpress.com/wp-admin/widgets.php). Currently, a customer has to install third party plugins [like this one](https://wordpress.org/plugins/widget-for-eventbrite-api/), to add this feature.

Would it be possible to add the widget functionality to the Eventbrite API plugin, so that it would make life easier for users?

Thanks!

**Comment by kwight** [comment]
Hi @harishankerr , this plugin isn't under very active development, so I wouldn't expect anything any time soon, I'm afraid :/
