### ISSUE TITLE
Change the order of past events?

### ISSUE THREAD

**Issue by tclayson** [Automattic/eventbrite-api#70]
How can I change the order of events, so I can use Eventbrite_Query to see past events starting with the most the most recently past event?

Thanks for the help!

**Comment by kwight** [comment]
`Eventbrite_Query` extends `WP_Query` so you should be able to work with the `order` [parameter](https://developer.wordpress.org/reference/classes/wp_query/#order-orderby-parameters) (but a search suggests [that may need some work](https://github.com/Automattic/eventbrite-api/commit/b669e6023bde36fa453feee2979987acf698b344)). There's also an `eventbrite_query_args` filter that could be helpful.

If you're working directly with the `user_owned_events` endpoint, there's an `order_by` [parameter](https://github.com/Automattic/eventbrite-api/blob/ca46b746780bc0b96d86bc4fc8180f645e33f059/inc/class-eventbrite-manager.php#L332).

Hope that helps, good luck.
