### ISSUE TITLE
Public events not showing

### ISSUE THREAD

**Issue by ducaannalise** [Automattic/eventbrite-api#82]
We are using the Eventbrite Wordpress api, and it seems that for some reason, Eventbrit public events are not showing. The events (public and private) only show IF the eventsbrite-api-display-private-events is active. If I disable the Eventbrite wordpress plugin (this one), NO events are displayed.

**Comment by kwight** [comment]
So, the events you expect are shown, but are identified as private? Can you give an example URL of one of the public events?

Also, try #71 ; it has updates beyond what have made it into `master`. Note that this repo is not under very active development.

**Comment by annaliseduca** [comment]
Thanks for your reply.

I don't know what happened (must have been an update or something) but now things are working as they should, and only public events are showing.

Thanks

**Comment by kwight** [comment]
👍
